sudo: required
services:
  - docker

before_install:
  - docker build -t alejandroconversica/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alejandroconversica/docker-react-test npm test

after_success:
  - docker build -t alejandroconversica/multi-client ./client
  - docker build -t alejandroconversica/multi-nginx ./nginx
  - docker build -t alejandroconversica/multi-server ./server
  - docker build -t alejandroconversica/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push alejandroconversica/multi-client
  - docker push alejandroconversica/multi-nginx 
  - docker push alejandroconversica/multi-server
  - docker push alejandroconversica/multi-worker

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "Momstm Cron"
  env: "Momstmcron-env"
  bucket_name: "elasticbeanstalk-us-west-2-247813293886"
  bucket_path: "Momstm Cron"
  on:
    branch: master

language: generic