version: "3.9"
services:
    client:
        image: "alejandroconversica/multi-client"
        mem_limit: 128m
        hostname: client
    server:
        image: "alejandroconversica/multi-server"
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
    worker:
        image: "alejandroconversica/multi-worker"
        mem_limit: 128m
        hostname: worker
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
    nginx:
        image: "alejandroconversica/multi-nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
            - "80:80"